// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	schema "github.com/goto/stencil/core/schema"
	mock "github.com/stretchr/testify/mock"
)

// SchemaProvider is an autogenerated mock type for the Provider type
type SchemaProvider struct {
	mock.Mock
}

// ParseSchema provides a mock function with given fields: format, data
func (_m *SchemaProvider) ParseSchema(format string, data []byte) (schema.ParsedSchema, error) {
	ret := _m.Called(format, data)

	if len(ret) == 0 {
		panic("no return value specified for ParseSchema")
	}

	var r0 schema.ParsedSchema
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []byte) (schema.ParsedSchema, error)); ok {
		return rf(format, data)
	}
	if rf, ok := ret.Get(0).(func(string, []byte) schema.ParsedSchema); ok {
		r0 = rf(format, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(schema.ParsedSchema)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = rf(format, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSchemaProvider creates a new instance of SchemaProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSchemaProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *SchemaProvider {
	mock := &SchemaProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
