// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	search "github.com/goto/stencil/core/search"
	mock "github.com/stretchr/testify/mock"
)

// SearchService is an autogenerated mock type for the SearchService type
type SearchService struct {
	mock.Mock
}

// Search provides a mock function with given fields: ctx, req
func (_m *SearchService) Search(ctx context.Context, req *search.SearchRequest) (*search.SearchResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *search.SearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *search.SearchRequest) (*search.SearchResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *search.SearchRequest) *search.SearchResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*search.SearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *search.SearchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSearchService creates a new instance of SearchService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearchService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchService {
	mock := &SearchService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
