global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'statsd_exporter'
    static_configs:
      - targets: ['localhost:9102']

  - job_name: 'success_count'
    static_configs:
      - targets: ['localhost:9102']
    metrics_path: /metrics
    params:
      match[]:
        - kafka_integration_success_count_total

  - job_name: 'failure_count'
    static_configs:
      - targets: ['localhost:9102']
    metrics_path: /metrics
    params:
      match[]:
        - kafka_integration_failure_count_total

  - job_name: 'latency'
    static_configs:
      - targets: ['localhost:9102']
    metrics_path: /metrics
    params:
      match[]:
        - kafka_integration_latency_seconds
