name: docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Installation
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
          working-directory: docs
      - name: Build docs
        working-directory: docs
        run: cd docs && yarn build
      - name: Deploy docs
        env:
          GIT_USER: github-actions[bot]
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
          DEPLOYMENT_BRANCH: gh-pages
          CURRENT_BRANCH: main
        working-directory: docs
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          yarn deploy
